repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    - id: ruff
      args: [--fix]
    # ruff-format disabled

- repo: local
  hooks:
    - id: dummy-hook
      name: dummy-hook-for-structure
      entry: echo "No hooks running"
      language: system
      pass_filenames: false
      always_run: false
    # pytest-fast disabled