NOT_YET_IMPLEMENTED_StmtImport
NOT_YET_IMPLEMENTED_StmtImport
NOT_YET_IMPLEMENTED_StmtImport
NOT_YET_IMPLEMENTED_StmtImportFrom
NOT_YET_IMPLEMENTED_StmtImportFrom

# Constantes para penalizaciones
NOT_YET_IMPLEMENTED_StmtAssign  # Factor base de penalización
NOT_YET_IMPLEMENTED_StmtAssign  # Penalización por exceso de capacidad
NOT_YET_IMPLEMENTED_StmtAssign  # Penalización por nodos faltantes (mayor)


NOT_YET_IMPLEMENTED_StmtClassDef
